import { createContext, useContext, useMemo, useState } from "react";
const translations={
 en:{brand:"MOD Camp",home:"Home",book:"Book",map:"Map",instructions:"Instructions",dashboard:"My Bookings",staff:"Staff",assistant:"Assistant",contact:"Contact",login:"Login",register:"Register",logout:"Logout",title:"MOD Camp Booking System",intro:"A one-day camp experience in Sabhan, Kuwait with tents, restaurants, shops, mosque, public bathrooms, and a theater.",location:"Location: Sabhan, Kuwait",opening:"Open from morning until 11:00 PM",oneDay:"Booking is for one day only",availableTents:"Available Tent Types",bookNow:"Book Now",selectTent:"Select Tent",capacity:"Capacity",price:"Price",bathroom:"Bathroom",bookingTitle:"Book Your Tent",captcha:"Captcha",captchaHelp:"Type the number shown above",submitBooking:"Submit Booking",confirmTitle:"Booking Confirmation",dashboardTitle:"My Bookings",staffTitle:"Staff Dashboard",staffLoginTitle:"Staff Login",confirm:"Confirm",cancel:"Cancel",status:"Status",campMap:"Camp Map",mapTitle:"Sabhan Camp Location",instructionsTitle:"Booking Instructions",assistantTitle:"MOD Assistant",contactTitle:"Contact Us",loginTitle:"User Login",registerTitle:"Create Account"},
 ar:{brand:"مخيم MOD",home:"الرئيسية",book:"الحجز",map:"الخريطة",instructions:"التعليمات",dashboard:"حجوزاتي",staff:"الموظفين",assistant:"المساعد",contact:"تواصل",login:"دخول",register:"تسجيل",logout:"خروج",title:"نظام حجز مخيم MOD",intro:"تجربة مخيم ليوم واحد في صبحان، الكويت، مع خيام ومطاعم ومحلات ومسجد وحمامات عامة ومسرح.",location:"الموقع: صبحان، الكويت",opening:"الدخول من الصباح حتى الساعة 11:00 مساءً",oneDay:"الحجز ليوم واحد فقط",availableTents:"أنواع الخيام المتوفرة",bookNow:"احجز الآن",selectTent:"اختر الخيمة",capacity:"السعة",price:"السعر",bathroom:"الحمام",bookingTitle:"احجز خيمتك",captcha:"التحقق",captchaHelp:"اكتب الرقم الظاهر بالأعلى",submitBooking:"إرسال الحجز",confirmTitle:"تأكيد الحجز",dashboardTitle:"حجوزاتي",staffTitle:"لوحة الموظفين",staffLoginTitle:"دخول الموظفين",confirm:"تأكيد",cancel:"إلغاء",status:"الحالة",campMap:"خريطة المخيم",mapTitle:"موقع المخيم في صبحان",instructionsTitle:"تعليمات الحجز",assistantTitle:"مساعد MOD",contactTitle:"تواصل معنا",loginTitle:"دخول المستخدم",registerTitle:"إنشاء حساب"}
};
const LanguageContext=createContext(null);
export function LanguageProvider({children}){
 const [language,setLanguage]=useState(localStorage.getItem("mod_language")||"en");
 const toggleLanguage=()=>{const next=language==="en"?"ar":"en";setLanguage(next);localStorage.setItem("mod_language",next);document.documentElement.dir=next==="ar"?"rtl":"ltr";document.documentElement.lang=next;};
 const value=useMemo(()=>({language,t:translations[language],toggleLanguage}),[language]);
 return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage(){return useContext(LanguageContext);}
